# Generated by Django 3.1.3 on 2021-01-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='imgWo',
            field=models.CharField(default='default title', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
