# Generated by Django 3.1.3 on 2021-01-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210121_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='imgWo',
        ),
    ]
