# Generated by Django 3.1.3 on 2021-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_books_imgwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
